image: golang:latest

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE/deployer
  IMAGE_TAG: "1.0"

stages:
  - build

build:
  stage: build
  image: docker:26.1.3
  services:
    - docker:26.1.3-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
