services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web1
      - web2
  web1:
    image: php:apache
    ports:
      - "9091:80"
    volumes:
      - ./web1/index.php:/var/www/html/index.php
    environment:
      WEB1URL: "http://web1.${DOMAIN}"
      WEB2URL: "http://web2.${DOMAIN}"
  web2:
    image: php:apache
    ports:
      - "9092:80"
    volumes:
      - ./web2/index.php:/var/www/html/index.php
    environment:
      WEB1URL: "http://web1.${DOMAIN}"
      WEB2URL: "http://web2.${DOMAIN}"
