apiVersion: v2
name: deployer
description: Manages challenges
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: postgresql
    version: "15.5.29"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: reflector
    version: "7.1.288"
    repository: https://emberstack.github.io/helm-charts
    condition: reflector.enabled
  - name: unleash
    version: "5.4.0"
    repository: https://docs.getunleash.io/helm-charts
    condition: unleash.enabled
