replicaCount: 1

image:
  repository: registry.gitlab.com/ctf9215737/ctf/deployer
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels:
  app: deployer

podSecurityContext: {}

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1001

service:
  type: ClusterIP
  port: 8080

volumes:
- name: deployer-pv-storage
  persistentVolumeClaim:
    claimName: deployer-pvclaim

volumeMounts:
- name: deployer-pv-storage
  mountPath: "/uploads"
  readOnly: false

livenessProbe:
  httpGet:
    path: /health
    port: 8080
readinessProbe:
  httpGet:
    path: /health
    port: 8080

ingress:
  create: true
  host: deployer.local.lan
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/issuer: "step-issuer"
    cert-manager.io/issuer-kind: "StepIssuer"
    cert-manager.io/issuer-group: "certmanager.step.sm"
  useTls: true
  tlsSecretName: "step-tls"

env:
  DBHOST: "deployer-postgresql"
  DBPORT: 5432
  DBUSER: "postgres"
  DBNAME: "postgres"
  # Directory of mounted storage where challenges are uploaded
  UPLOADPATH: "/uploads"
  # Min and max allowed memory used by VM
  MINVMMEMORY: "256M"
  MAXVMMEMORY: "2048M"
  # Minutes before challenge instances are automatically deleted
  CHALLENGELIFETIMEMINUTES: 120
  # URL where VM's can download challenge files from the deployer service
  BACKENDURL: "http://deployer.ctf.svc.cluster.local:8080"
  # The domain of which subdomains are generated, example: 7651121c-b8d2-43e9-af88-c493d8ad8a75.local.lan
  CHALLENGEDOMAIN: ".local.lan"
  VMIMAGEURL: "registry.gitlab.com/ctf9215737/ctf/alpinevm"
  # URL where the deployer service can access CTFd
  CTFDURL: "http://ctfd"
  CTFDAPITOKEN: "ctfd_..."
  GIN_MODE: "release"

# PostgreSQL subchart: Use own secret to avoid replacing the Postgres secret on upgrade
postgresql:
  auth:
    existingSecret: deployer-postgresql

