apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: deployerhttps
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.ingress.host }}`)
    services:
    - name: {{ include "helm.fullname" . }}
      port: 8080
