apiVersion: v1
kind: Secret
metadata:
  name: deployer
  annotations:
    "helm.sh/resource-policy": "keep"
data:
  password: {{ randAlphaNum 32 | b64enc }}
  jwtsecret: {{ randAlphaNum 32 | b64enc }}
