services:
  openssh-server:
    image: lscr.io/linuxserver/openssh-server:latest
    environment:
      - PUID=1000
      - PGID=1000
      - SUDO_ACCESS=false
      - PASSWORD_ACCESS=true
      - USER_PASSWORD=test
      - USER_NAME=test
    ports:
      - "${SSH_PORT-127.0.0.1:2222}:2222"
    volumes:
      - ./flag.txt:/flag.txt:ro
    restart: unless-stopped

  web1:
    image: php:apache
    volumes:
      - ./web1/index.php:/var/www/html/index.php
    restart: unless-stopped

  web2:
    image: php:apache
    volumes:
      - ./web2/index.php:/var/www/html/index.php
    restart: unless-stopped

  healtcheck:
    build: ./healthcheck
    ports:
      - "${HTTP_PORT-127.0.0.1:8080}:8080"
    restart: unless-stopped
