services:
  nginx:
    image: nginx:latest
    ports:
      - "${HTTP_PORT-127.0.0.1:8080}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web1
      - web2
    restart: unless-stopped

  web1:
    image: php:apache
    volumes:
      - ./web1/index.php:/var/www/html/index.php
    environment:
      WEB1URL: "http://web1.${DOMAIN}"
      WEB2URL: "http://web2.${DOMAIN}"
    restart: unless-stopped

  web2:
    image: php:apache
    volumes:
      - ./web2/index.php:/var/www/html/index.php
    environment:
      WEB1URL: "http://web1.${DOMAIN}"
      WEB2URL: "http://web2.${DOMAIN}"
    restart: unless-stopped
