apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: network-policy
spec:
  podSelector:
    matchLabels:
      app: deployer
  ingress:
    - ports:
        - port: 8080
  policyTypes:
    - Ingress
