apiVersion: v1
kind: Secret
metadata:
  name: deployer
  annotations:
    "helm.sh/resource-policy": "keep"
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "password") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $password := (get $secretData "password") | default (randAlphaNum 32 | b64enc) }}
  password: {{ $password | quote }}
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "jwtsecret") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $jwtSecret := (get $secretData "jwtsecret") | default (randAlphaNum 32 | b64enc) }}
  jwtsecret: {{ $jwtSecret | quote }}
