apiVersion: v1
kind: Secret
metadata:
  name: deployer
data:
  {{- if .Release.IsInstall }}
  password: {{ randAlphaNum 32 | b64enc | quote }}
  {{ else }}
  password:  {{ index (lookup "v1" "Secret" .Release.Namespace "deployer" | default (dict "data" (dict "password" (randAlphaNum 32 | b64enc)))).data "password" }}
  {{ end }}

  {{- if .Release.IsInstall }}
  jwtsecret: {{ randAlphaNum 32 | b64enc | quote }}
  {{ else }}
  jwtsecret:  {{ index (lookup "v1" "Secret" .Release.Namespace "deployer" | default (dict "data" (dict "jwtsecret" (randAlphaNum 32 | b64enc)))).data "jwtsecret" }}
  {{ end }}
